import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const arr = [
    {
      id: "1",
      name: "lam quang vinh 1",
      age: 22,
    },
    { id: "2", name: "lam quang vinh 2", age: 22 },
    { id: "3", name: "lam quang vinh 3", age: 22 },
  ];
  const [arrList, setArrList] = useState(arr);
  return (
    <div className="w-full h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        {arrList.map((item, index) => {
          return (
            <div className="" key={item.id}>
              {item.name}
            </div>
          );
        })}
      </div>
      <button
        className=""
        onClick={() => {
          arr.splice(1, 1);
          setArrList([...arr]);
        }}
      >
        xoa item giua
      </button>
    </div>
  );
}
