module.exports.Token = require('./token.model')
module.exports.User = require('./user.model')
module.exports.Author = require('./author.model')
module.exports.Book = require('./book.model')
module.exports.Category = require('./category.model')
